### ISSUE TITLE
Individual lines need delimiter choice of CR+LF or LF instead of line feed only

### ISSUE THREAD

**Issue by ProBackup-nl** [kaarposoft/qrlogo#4]
The encode form at http://qrlogo.kaarposoft.dk/qrencode.html is used to produce a vCard QR code.
There are multiple lines pasted into the text box.

Current output using Safari on Mac OS X:
Individual lines are delimited by the (Unix style) **LF** (10) sequence.

Needed output according to RFC6350 (the vCard format spec):
Individual lines within vCard are delimited by the [RFC5322] line break, which is a **CRLF** (13,10) sequence

**Comment by kaarposoft** [comment]
Fixed in commit 79c909960b298c511e5730a47d727b3e4267650e
