### ISSUE TITLE
short url/text does not work

### ISSUE THREAD

**Issue by othmar52** [kaarposoft/qrlogo#5]
For some reason i dont get a result when trying to embed very short urls.
As a test bitmap i used a single colored .gif with 123x123 pixels

the text/urls i tried to encode:
`http://po/cf/` no result
`http://po/cf/foo.htm` no result
`http://po.com/cf/` no result
`http://po.lan/` no result
`http://bit.ly/123` no result
`http://po.com/cf/foo.htm` works
`http://github.com/very-long-url/with-many-characters` works

Is this a bug? or am i missing something here?
i tried with firefox and chromium

**Comment by kaarposoft** [comment]
Fixed in commit 198056aefcbe08b5ddd5179ea138e414ff521fc1
